export const Games = [
    { value: 'red', viewValue: 'Red' },
    { value: 'blue', viewValue: 'Blue' },
    { value: 'yellow', viewValue: 'Yellow' },
    { value: 'stadium', viewValue: 'Stadium' },
    { value: 'gold', viewValue: 'Gold' },
    { value: 'silver', viewValue: 'Silver' },
    { value: 'crystal', viewValue: 'Crystal' },
    { value: 'stadium2', viewValue: 'Stadium 2' },
    { value: 'ruby', viewValue: 'Ruby' },
    { value: 'sapphire', viewValue: 'Sapphire' },
    { value: 'emerald', viewValue: 'Emerald' },
    { value: 'firered', viewValue: 'Firered' },
    { value: 'leafgreen', viewValue: 'Leafgreen' },
    { value: 'diamond', viewValue: 'Diamond' },
    { value: 'pearl', viewValue: 'Pearl' },
    { value: 'platinum', viewValue: 'Platinum' },
    { value: 'heartgold', viewValue: 'HeartGold' },
    { value: 'soulsilver', viewValue: 'SoulSilver' },
    { value: 'black', viewValue: 'Black' },
    { value: 'white', viewValue: 'White' },
    { value: 'black2', viewValue: 'Black 2' },
    { value: 'white2', viewValue: 'White 2' },
    { value: 'x', viewValue: 'X' },
    { value: 'y', viewValue: 'Y' },
    { value: 'omegaRuby', viewValue: 'Omega Ruby' },
    { value: 'alphaSapphire', viewValue: 'Alpha Sapphire' },
    { value: 'sun', viewValue: 'Sun' },
    { value: 'moon', viewValue: 'Moon' },
    { value: 'ultraSun', viewValue: 'Ultra Sun' },
    { value: 'ultraMoon', viewValue: 'Ultra Moon' },
    { value: 'letsGoPikachu', viewValue: "Let's Go Pikachu" },
    { value: 'letsGoEevee', viewValue: "Let's Go Eevee" },
    { value: 'sword', viewValue: 'Sword' },
    { value: 'shield', viewValue: 'Shield' },
    { value: 'brilliantDiamond', viewValue: 'Brilliant Diamond' },
    { value: 'shiningPearl', viewValue: 'Shining Pearl' },
    { value: 'legendsArceus', viewValue: 'Legends Arceus' }
  ];